spring.application.name=customer-service
server.port=8082

# MYSQL Connectivity

spring.datasource.url=jdbc:mysql://localhost:3306/customerservice?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=MySQL@100
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# Kafka
spring.kafka.boostrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.header=false

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoints.health.show-details=always

# SWAGGER
spring.doc.api-docs.path=/v3/api-docs
spring.doc.swagger-ui.path=/swagger-ui.html
spring.doc.swagger-ui.operations-sorter=method
spring.doc.swagger-ui.tags-sorter=alpha

# LOGGING
logging.level.root=INFO
logging.level.com.microservice.customerservice=debug
logging.level.org.apache.camel=INFO
logging.level.org.hibernate.SQL=INFO






